webtalk_init -webtalk_dir /home/chakenal/Darwin-WGA-hw-emu/_xocc_link_BSW_bank0_WGA.hw_emu.dir/_vpl/ipi/syn/syn.sim/sim_1/behav_gdb/xsim/xsim.dir/emu_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 28 21:09:22 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4.op (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2193837" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c64ac326-2236-44aa-ba7a-072f30c33cda" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "15af5c13228c426a8e9753f1800cd4ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2696 v4 @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1197.738 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "135.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "188" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "off" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "8155 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "5768 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "137721" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "6141" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "41.49_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "2047824_KB" -context "xsim\\usage"
webtalk_transmit -clientid 19051463 -regid "211842992_0_0_525" -xml /home/chakenal/Darwin-WGA-hw-emu/_xocc_link_BSW_bank0_WGA.hw_emu.dir/_vpl/ipi/syn/syn.sim/sim_1/behav_gdb/xsim/xsim.dir/emu_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/chakenal/Darwin-WGA-hw-emu/_xocc_link_BSW_bank0_WGA.hw_emu.dir/_vpl/ipi/syn/syn.sim/sim_1/behav_gdb/xsim/xsim.dir/emu_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/chakenal/Darwin-WGA-hw-emu/_xocc_link_BSW_bank0_WGA.hw_emu.dir/_vpl/ipi/syn/syn.sim/sim_1/behav_gdb/xsim/xsim.dir/emu_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
