#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4.op (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sat Dec 28 21:08:29 IST 2019
# SW Build 2193837 on Tue Apr 10 18:06:59 MDT 2018
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvlog --incr --relax -L xil_defaultlib -prj emu_wrapper_vlog.prj"
ExecStep xvlog --incr --relax -L xil_defaultlib -prj emu_wrapper_vlog.prj 2>&1 | tee compile.log
echo "xvhdl --incr --relax -prj emu_wrapper_vhdl.prj"
ExecStep xvhdl --incr --relax -prj emu_wrapper_vhdl.prj 2>&1 | tee -a compile.log
